### ISSUE TITLE
purescript-difflists broken from commit to purescript-unfoldable

### ISSUE THREAD

**Issue by clinuxrulz** [Thimoteus/purescript-difflists#2]
see: https://github.com/purescript/purescript-unfoldable/commit/dba1daf9024c25eb0e9de7dc511f5e0f0d366300

the new function "singleton" in Data.Unfoldable clashes with Data.DList and Data.DArray.

removing your "singleton" functions makes it work.

OR

import Data.Unfoldable hiding (singleton), also makes it work.

**Comment by Thimoteus** [comment]
Hmm, it looks like I had already fixed this but just didn't push the new tag up to github. Thanks!
