### ISSUE TITLE
name in bower.json does not agree with name on Bower

### ISSUE THREAD

**Issue by hdgarrood** [Thimoteus/purescript-difflists#3]
The reason this package has disappeared from Pursuit is that the reupload script failed, because the name in bower.json disagrees with the name on Bower. Sorry.

First step should be to fix that and publish a new version, I think. Do you mind about the older versions missing from Pursuit?

**Comment by hdgarrood** [comment]
By the way, you might think that this re-uploading business is all a bit ad-hoc, and you'd be right. We're not planning to regularly break the JSON format, so this shouldn't happen often.

**Comment by Thimoteus** [comment]
Finally got around to [reuploading](https://pursuit.purescript.org/packages/purescript-difflists/3.0.1-pursuit).

As to the older versions that are missing, there's a chance they relied on compiler behavior that's since been disallowed, so documentation for them shouldn't be on Pursuit anyway.
